### PR TITLE
feat: support sse and neon

### PR DESCRIPTION
**Pull request by xiegx94**
# Main changes
Support `sse` and `neon` simd.

### CODE REVIEW

**Comment by xiegx94** [comment]
fix #50

**Comment by liuq19** [comment]
can we have a fallback code to support all other env?

**Comment by xiegx94** [comment]
> can we have a fallback code to support all other env?

But sonic has copied origin json string and pad it to avoid crossing memory boundary by simd codes.

**Comment by liuq19** [comment]
> > can we have a fallback code to support all other env?
> 
> But sonic has copied origin json string and pad it to avoid crossing memory boundary by simd codes.

performance may be not import for fallback impl，we can just make a very naive fallback impl as simdjson

**Comment by xiegx94** [comment]
#56 is better

**Pull request closed without merging**
